export const TEST_URL = 'http://localhost:3000'
export const TEST_CIRCLE_CONTAINER = '[data-testid=circleContainer]'
export const TEST_CIRCLE = '[data-testid=circle]'
export const TEST_HEAD_CIRCLE = '[data-testid=head]'
export const TEST_LETTER_CIRCLE = '[data-testid=letter]'
export const TEST_INDEX_CIRCLE = '[data-testid=index]'
export const TEST_TAIL_CIRCLE = '[data-testid=tail]'
export const TEST_ADD_BUTTON = '[data-testid=addButton]'
export const TEST_REMOVE_BUTTON ='[data-testid=removeButton]'
export const TEST_CLEAR_BUTTON = '[data-testid=clearButton]'
export const TEST_INPUT = '[data-testid=input]'
